name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn build
    - name: Lint
      run: yarn lint
    - name: Run tests
      run: yarn test
